name: Build project

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    name: Build and Deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Deploy project
        run: npm run action:githubPages -- --name $GITHUB_ACTOR --email $GITHUB_ACTOR@users.noreply.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
